### ISSUE TITLE
Best way to shutdown on exit?

### ISSUE THREAD

**Issue by amcdnl** [dewe/nginx-server#3]
I'm trying to kill the process when the server exits, I'm thinking something like this:

```
  process.on('beforeExit', function() {
    server.stop();
  });
```

but it doesn't always work. This is probably sometime you need to handle internally too tho. Thoughts?

**Comment by dewe** [comment]
Is it not stopping the process, or is it never calling the callback? 

That code is just issuing a call to `nginx` and waiting for process to close. Probably there's better and more robust ways to do that, possibly involving keeping track of the PID file...

**Comment by amcdnl** [comment]
Yup, looked through the code and did not see anything crazy but in researching I did find this comment: https://nodejs.org/api/process.html#process_event_exit

Agreed, re: the pid.

**Comment by dewe** [comment]
Hmm, yeah since nginx is in a separate process, it's kind of hard to be synchronous with that... I'll think about it for a while. If you come up with something, please let me know.

**Comment by amcdnl** [comment]
Will do!

**Comment by dewe** [comment]
I've been trying to reproduce this issue, with no luck. When calling server.stop() in the `exit` event callback, the nginx server receives the correct signal and shuts down after a very short time. It's sort of a race condition: the node process might shutdown before nginx is done closing, but I haven't been observing any nginx processes left running for more than a few milliseconds.

One thing I found though: the `exit` event doesn't seem to be reliable. When killing node with Ctrl-C it just doesn't trigger an `exit` event. But if I call process.exit() it works like a charm...

@amcdnl Any thoughts on this? Did you verify that the `exit`event really happens?

**Comment by amcdnl** [comment]
> When killing node with Ctrl-C it just doesn't trigger an exit event. But if I call process.exit() it works like a charm...

I was using ctrl+c ... makes sense ... wonder why that is!

**Comment by dewe** [comment]
For catching Ctrl-C and closing the server, use something like this (not tested):

```
process.on('exit', () => server.close());
process.on('SIGINT', () => process.exit());
```

**Comment by dewe** [comment]
Found a bit more info here: https://github.com/nodejs/node/issues/2853

**Comment by amcdnl** [comment]
Would be nice to incorporate this into the project. ;)

**Comment by amcdnl** [comment]
FYI -> `server.stop()` ;)

**Comment by amcdnl** [comment]
> Note that even though the name of this function is `process.kill`, it is really just a signal sender, like the `kill` system call.  The signal sent may do something other than kill the target process.

I'm on windows, could be my issue.

**Comment by amcdnl** [comment]
FYI: this seemed to do the trick:

```
  // http://stackoverflow.com/questions/5006821/nodejs-how-to-read-keystrokes-from-stdin
  var stdin = process.stdin;
  stdin.setRawMode(true);
  stdin.resume();
  stdin.setEncoding('utf8');
  stdin.on('data', function(key){
    // ctrl-c
    if (key === '\u0003') {
      console.log('EXITING!')
      server.stop(function() {
        process.exit();
      });
    }
  });
```

**Comment by amcdnl** [comment]
I'm closing this since got a work around.
